# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 07:13
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='country',
            field=django_countries.fields.CountryField(default='Germany', max_length=2, verbose_name='Country'),
        ),
    ]
