# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0002_participant_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birthdate',
            field=models.DateField(default='', verbose_name='Date of Birth'),
        ),
    ]
