# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0003_auto_20160408_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPersonalityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guratorapp.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionA', models.CharField(max_length=500, verbose_name='A')),
                ('optionB', models.CharField(max_length=500, verbose_name='B')),
            ],
        ),
        migrations.AddField(
            model_name='participantpersonalityquestion',
            name='personality_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guratorapp.PersonalityQuestion'),
        ),
        migrations.AddField(
            model_name='participant',
            name='personality_answers',
            field=models.ManyToManyField(through='guratorapp.ParticipantPersonalityQuestion', to='guratorapp.PersonalityQuestion'),
        ),
    ]
