# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0004_auto_20160410_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='personality_test_done',
            field=models.BooleanField(default=False, verbose_name='Personality test done'),
        ),
    ]
