# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0005_participant_personality_test_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_capital', models.IntegerField()),
                ('tie_strength', models.IntegerField()),
                ('social_similarity', models.IntegerField()),
                ('social_context_similarity', models.IntegerField()),
                ('sympathy', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_participant', to='guratorapp.Participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_participant', to='guratorapp.Participant')),
            ],
        ),
    ]
