# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0006_usersurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_yelp_id', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('taste', models.IntegerField()),
                ('clumsiness', models.IntegerField()),
                ('service', models.IntegerField()),
                ('hippieness', models.IntegerField()),
                ('location', models.IntegerField()),
                ('social_overlap', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_rating_the_restaurant', to='guratorapp.Participant')),
            ],
        ),
    ]
