# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0007_restaurantsurvey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantsurvey',
            old_name='resturant_yelp_id',
            new_name='restaurant_yelp_id',
        ),
    ]
