# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0008_auto_20160509_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsurvey',
            name='other',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
