# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0009_restaurantsurvey_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='domain_expertise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='social_hierarchy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurantsurvey',
            name='clumsiness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurantsurvey',
            name='hippieness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurantsurvey',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurantsurvey',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurantsurvey',
            name='service',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurantsurvey',
            name='social_overlap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurantsurvey',
            name='taste',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='social_capital',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='social_context_similarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='social_similarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='sympathy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='tie_strength',
            field=models.IntegerField(default=0),
        ),
    ]
