# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0011_auto_20160510_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='groups',
            field=models.ManyToManyField(through='guratorapp.GroupParticipant', to='guratorapp.Group'),
        ),
    ]
