# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0012_participant_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRestaurantSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_yelp_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('taste', models.IntegerField(default=0)),
                ('clumsiness', models.IntegerField(default=0)),
                ('service', models.IntegerField(default=0)),
                ('hippieness', models.IntegerField(default=0)),
                ('location', models.IntegerField(default=0)),
                ('social_overlap', models.IntegerField(default=0)),
                ('other', models.CharField(blank=True, max_length=1000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rating_the_restaurant', to='guratorapp.Group')),
            ],
        ),
    ]
