# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0013_grouprestaurantsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='relationship',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
