# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0014_usersurvey_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='personality',
            field=models.CharField(choices=[('competing', 'Competing'), ('cooperating', 'Cooperating'), ('compromising', 'Compromising'), ('avoiding', 'Avoiding'), ('accommodating', 'Accommodating'), ('df', 'Default')], default='df', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalityquestion',
            name='optionA',
            field=models.CharField(max_length=1000, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='personalityquestion',
            name='optionB',
            field=models.CharField(max_length=1000, verbose_name='B'),
        ),
    ]
