# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0015_auto_20180226_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityquestion',
            name='name',
            field=models.CharField(default='no name', max_length=10),
        ),
    ]
