# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0017_auto_20180316_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouprestaurantsurvey',
            old_name='restaurant_yelp_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='restaurantsurvey',
            old_name='restaurant_yelp_id',
            new_name='restaurant_id',
        ),
    ]
