# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0018_auto_20180414_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='personality_accommodating',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='personality_avoiding',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='personality_competing',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='personality_compromising',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='personality_cooperating',
        ),
        migrations.RemoveField(
            model_name='personalityquestion',
            name='name',
        ),
    ]
