# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0019_auto_20180420_2318'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (1,'I try to find a compromise solution','I attempt to deal with all of his and my concerns');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (2,'There are times when I let others take responsibility for solving the problem','Rather than negotiate the things on which we disagree, I try to stress those things upon which we both agree');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (3,'I am usually firm in pursuing my goals','I might try to soothe the other''s feelings and preserve our relationship');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (4,'I try to find a compromise solution','I sometimes sacrifice my own wishes for the wishes of the other person');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (5,'I feel that the differences are not always worth worrying about','I make some effort to get my way');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (6,'I am usually firm in pursuing my goals','I attempt to get all concerns and issues immediately out in the open');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (7,'I try to postpone the issue until I have had some time to think it over','I give up some points in exchange for others');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (8,'I try to avoid creating unpleasantness for myself','I try to win my position');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (9,'I consistently seek the other''s help in working out a solution','I try to do what is necessary to avoid useless tensions');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (10,'I attempt to get all concerns and issues immediately out in the open','I might try to soothe the other''s feelings and preserve our relationship');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (11,'I am firm in pursuing my goals','I try to find a compromise solution');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (12,'I sometimes avoid taking positions which could create controversy','I will let him have some of his positions if he lets me have some of mine');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (13,'I attempt to immediately work through our differences','I try to find a fair combination of gains and losses for both of us');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (14,'I attempt to get all concerns and issues immediately out in the open','I try to postpone the issue until I have had time to think it over');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (15,'If it makes the other person happy, I might let him maintain his views','I will let him have some of his positions if he lets me have some of mine');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (16,'I am usually firm in pursuing my goals','I try to do what is necessary to avoid useless tensions');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (17,'I try not to hurt the other''s feelings','I try to convince the other person of the merits of my position');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (18,'I might try and soothe the other''s feelings and preserve our relationship','I try to do what is necessary to avoid tensions');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (19,'I tell him my ideas and ask him for his','I try to show him the logic and benefits of my position');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (20,'I propose a middle ground','I press to get my points made');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (21,'I try not to hurt the other''s feelings','I always share the problem with the other person so that we can work it out');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (22,'I propose a middle ground','I feel that the differences are not always worth worrying about');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (23,'I am usually firm in pursuing my goals','I usually seek the other''s help in working out a solution');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (24,'I sometimes avoid taking positions which could create controversy','If it makes the other person happy, I might let him maintain his views');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (25,'I propose a middle ground','I am nearly always concerned with satisfying all our wishes');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (26,'I try to show him the logic and benefits of my position','In approaching negotiations, I try to be considerate of the other person''s wishes');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (27,'If the other''s position seems very important to him, I would try to meet his wishes','I try to get him to settle for a compromise solution');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (28,'I am very often concerned with satisfying all our wishes','There are times when I let others take responsibility for solving the problem');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES (29,'I try to find a position that is intermediate between his and mine','I assert my wishes');"),
        migrations.RunSQL("INSERT INTO guratorapp_personalityquestion VALUES(30,'In approaching negotiations, I try to be considerate of the other person''s wishes','I always lean toward a direct discussion of the problem');"),
    ]
