# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0020_personality_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='device_id',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Device ID'),
        ),
    ]
