# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0021_participant_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='device_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Device ID'),
        ),
    ]
