# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guratorapp', '0023_group_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='internal',
            field=models.CharField(default='in', max_length=10, verbose_name='Internal group'),
        ),
    ]
